HoroScope/HoroScope/Models/BlogCategory.cs
using HoroScope.Models.Base;

namespace HoroScope.Models
{
    public class BlogCategory : BaseEntity
    {
        public string Name { get; set; }
        public List<Blog>? Blogs { get; set; }
    }
}

HoroScope/HoroScope/Areas/Admin/Controllers/BlogCategoryController.cs
using HoroScope.DAL;
using HoroScope.Models;
using HoroScope.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HoroScope.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class BlogCategoryController : Controller
    {
        private readonly AppDbContext _context;

        public BlogCategoryController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {

            List<GetBlogCategoryVM> blogCategoryVMs = await _context.BlogCategories
                .Where(bc => !bc.IsDeleted)
                .Select(sc => new GetBlogCategoryVM
                {
                    Id = sc.Id,
                    Name = sc.Name,
                    CreatedAt = sc.CreatedAt,
                    IsDeleted = sc.IsDeleted,
                }).ToListAsync();

            return View(blogCategoryVMs);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateBlogCategoryVM category)
        {
            if (!ModelState.IsValid)
            {
                return View(category);
            }

            bool result = await _context.BlogCategories
            .Where(cs => !cs.IsDeleted)
            .AnyAsync(cs => cs.Name == category.Name);

            if (result)
            {
                ModelState.AddModelError(nameof(CreateBlogCategoryVM.Name), $"This Category: {category.Name} already exists");
                return View(category);
            }

            BlogCategory BlogCategory = new()
            {
                Name = category.Name,
                CreatedAt = DateTime.Now
            };

            await _context.BlogCategories.AddAsync(BlogCategory);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null) return BadRequest();

            BlogCategory? category = await _context.BlogCategories
                .FirstOrDefaultAsync(bc => bc.Id == id && bc.IsDeleted == false);

            if (category is null) return NotFound();
            category.IsDeleted = true;
            _context.BlogCategories.Update(category);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> HardDelete(int? id)
        {
            if (id is null) return BadRequest();

            BlogCategory? category = await _context.BlogCategories
                .FirstOrDefaultAsync(sc => sc.Id == id);

            if (category is null) return NotFound();

            _context.BlogCategories.Remove(category);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Update(int? id)
        {
            if (id is null || id <= 0) return BadRequest();

            BlogCategory? category = await _context.BlogCategories.FirstOrDefaultAsync(sc => sc.Id == id);

            if (category is null) return NotFound();

            UpdateBlogCategoryVM categoryVM = new()
            {
                Name = category.Name,
            };

            return View(categoryVM);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int? id, UpdateBlogCategoryVM? categoryVM)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            bool result = await _context.BlogCategories.AnyAsync(c => c.Name == categoryVM.Name && c.Id != id);
            if (result)
            {
                ModelState.AddModelError(nameof(UpdateBlogCategoryVM.Name), $"This Category: This Category: {categoryVM.Name} is already exists");
                return View(categoryVM);
            }

            BlogCategory? existed = await _context.BlogCategories.FirstOrDefaultAsync(c => c.Id == id);

            if (existed.Name == categoryVM.Name) return RedirectToAction(nameof(Index));

            existed.Name = categoryVM.Name;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Restore(int? id)
        {
            if (id is null) return BadRequest();

            BlogCategory? category = await _context.BlogCategories
                .FirstOrDefaultAsync(sc => sc.Id == id && sc.IsDeleted == true);

            if (category is null) return NotFound();

            category.IsDeleted = false;
            _context.BlogCategories.Update(category);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(DeletedCategories));
        }
        public async Task<IActionResult> DeletedCategories()
        {
            var deletedCategories = await _context.BlogCategories
                .Where(sc => sc.IsDeleted == true)
                .ToListAsync();

            return View(deletedCategories);
        }
    }
}

HoroScope/HoroScope/Areas/Admin/Views/BlogCategory/Create.cshtml
@model CreateBlogCategoryVM

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create Blog Category</h4>

            <form method="post" class="forms-sample">

                <div class="form-group">
                    <label asp-for="Name">Name</label>
                    <input asp-for="Name" class="form-control" placeholder="Name">
                    <span class="text-danger" asp-validation-for="Name"></span>
                </div>

                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <button asp-action="index" class="btn btn-light">Cancel</button>
            </form>
        </div>
    </div>
</div>

HoroScope/HoroScope/Areas/Admin/Views/BlogCategory/DeletedCategories.cshtml
@model List<BlogCategory>

@{
    int count = 0;
}

<h2>Deleted Blog Categories</h2>

@if (!Model.Any())
{
    <div class="alert alert-info text-center">
        No deleted Blog Categories found.
    </div>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>No</th>
                <th>Name</th>
                <th>Setting</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var BlogCategory in Model)
            {
                count++;
                <tr>
                    <td>@count</td>
                    <td>@BlogCategory.Name</td>

                    <td>
                        <a asp-controller="BlogCategory" asp-action="Restore" asp-route-id="@BlogCategory.Id" class="btn btn-success">
                            <i class="mdi mdi-restore"></i>
                        </a>
                        <a asp-controller="BlogCategory" asp-action="HardDelete" asp-route-id="@BlogCategory.Id" class="btn btn-danger">
                            <i class="mdi mdi-delete-forever"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

<div style="margin-top: 20px;">
    <a asp-controller="BlogCategory" asp-action="Index" class="btn btn-secondary">Back to Blog Categories</a>
</div>

HoroScope/HoroScope/Areas/Admin/Views/BlogCategory/Index.cshtml
@model List<GetBlogCategoryVM>

@{
    int count = 0;
}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Blog Categories</h4>

            <a asp-controller="BlogCategory" asp-action="DeletedCategories" class="btn btn-danger">Show Deleted Categories</a>
            <a asp-controller="BlogCategory" asp-action="Create" class="btn btn-light">Create</a>

            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Name</th>
    
                            <th>Setting</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (GetBlogCategoryVM getBlogCategoryVM in Model)
                        {
                            count++;
                            <tr>
                                <td>@count</td>
                                <td>@getBlogCategoryVM.Name</td>
                   
                                <td>
 <a asp-controller="BlogCategory" asp-action="Update" asp-route-id="@getBlogCategoryVM.Id" class="btn btn-primary"><i class="mdi mdi-pencil-box"></i></a>
                                    <a asp-controller="BlogCategory" asp-action="Delete" asp-route-id="@getBlogCategoryVM.Id" class="btn btn-danger"
                                       onclick="return confirm('Are you sure you want to delete this Category?')">
                                        <i class="mdi mdi-delete-forever"></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

HoroScope/HoroScope/Areas/Admin/Views/BlogCategory/Update.cshtml
@model UpdateBlogCategoryVM

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Update Blog Category</h4>

            <form method="post" class="forms-sample">

                <div class="form-group">
                    <label asp-for="Name">Name</label>
                    <input asp-for="Name" class="form-control" placeholder="Name">
                    <span class="text-danger" asp-validation-for="Name"></span>
                </div>

                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <button asp-action="index" class="btn btn-light">Cancel</button>
            </form>
        </div>
    </div>
</div>